name: CI - Users Service

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Instalar dependências
        run: npm install

      - name: Buildar projeto
        run: npm run build